targets:
  $default:
    sources:
      include:
        - pubspec.yaml
        - lib/**
        - $package$
    builders:
      envied_generator|envied_generator:
        generate_for:
          - "**/env/**.dart"
      freezed|freezed:
        generate_for:
          - "**/entities/**.dart"
          - "**/value_objects/**.dart"
          - "**/view_models/**.dart"
      injectable_generator|injectable_generator:
        generate_for:
          - "**/infrastructure/**.dart"
      json_serializable|json_serializable:
        generate_for:
          - "**/dto/**.dart"
          - "**/entities/**.dart"
          - "**/infrastructure/**.dart"
          - "**/value_objects/**.dart"
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.

          # The default values
          any_map: false
          checked: false
          constructor: ""
          create_factory: true
          # create_field_map: false
          create_to_json: true
          disallow_unrecognized_keys: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true

          # Not default values
          explicit_to_json: true
      mobx_codegen|mobx_codegen:
        generate_for:
          - "**/stores/**.dart"
      retrofit_generator|retrofit_generator:
        generate_for:
          - "**/infrastructure/**.dart"