name: itrust
description: ITrust social network.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  another_flushbar: ^1.12.29
  cloud_firestore: ^4.3.1
  collection: ^1.16.0
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.5
  drift: ^2.4.2
  equatable: ^2.0.5
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flutter_hooks: ^0.18.5+1
  flutter_mobx: ^2.0.6+5
  flutter_native_splash: ^2.2.17
  flutter_svg: ^1.1.6
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^6.0.1
  injectable: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  logging: ^1.1.0
  mobx: ^2.1.3
  rxdart: ^0.27.7
  transparent_image: ^2.0.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  flutter_gen_runner: ^5.1.0+1
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  injectable_generator: ^2.1.3
  json_serializable: ^6.5.4
  mobx_codegen: ^2.1.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/image/png/
    - assets/image/svg/

flutter_gen:
  output: lib/gen/

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
