name: itrust
description: ITrust social network.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  another_flushbar: ^1.12.29
  cached_network_image: ^3.2.3
  collection: ^1.16.0
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.5
  device_info_plus: ^8.1.0
  dio: ^5.0.1
  envied: ^0.3.0
  equatable: ^2.0.5
  flutter_hooks: ^0.18.6
  flutter_mobx: ^2.0.6+5
  flutter_native_splash: ^2.2.18
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^1.1.6
  fpdart: ^0.4.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^6.0.9
  hive_flutter: ^1.1.0
  injectable: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.8.0
  logging: ^1.1.1
  lottie: ^2.3.2
  mapster: ^0.3.0
  mobx: ^2.1.4
  problem_details: ^0.0.2
  retrofit: ^4.0.1
  rxdart: ^0.27.7
  shimmer: ^2.0.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  flutter_gen_runner: ^5.1.0+1
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.1
  mobx_codegen: ^2.1.1
  retrofit_generator: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/image/png/
    - assets/image/svg/
    - assets/json/
    - assets/lottie/

flutter_gen:
  output: lib/gen/

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true