name: itrust
description: ITrust messenger.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.5
  drift: ^2.3.0
  equatable: ^2.0.5
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3

  flutter_lints: ^2.0.1
  mobx_codegen: ^2.1.1

flutter:
  uses-material-design: true
